export const NODE_TAG_MAPPING: Record<string, string> = {
  monitoring: "(process step) monitoring",
  tracing: "(process step) tracing",
  attribution: "(process step) attribution",
  "legal-action": "(process step) evidence management",
  prevention: "(process step) prevention",
  "all-in-one-tools": "(process step) all in one tools",

  "rule-based": "(method) rule-based",
  clustering: "(method) clustering",
  "heuristic-based": "(method) heuristic-based",
  bitcoin: "(token) bitcoin",
  "graph-based": "(method) graph-based",
  "visualization-tools": "visualization tool",
  nlp: "(method) nlp",
  "named-entity-recognition": "named entity recognition",
  "sentiment-analysis": "(method) sentiment analysis",
  "machine-learning": "(method) machine learning",
  "generative-ai": "(method) gen-ai",
  "monitoring-ai": "(method) ai-based",
  "monitoring-rule": "(method) rule-based",
  "evidence-management": "evidence management",
  "entity-databases": "database",
};
